# Generated by Django 2.0 on 2018-01-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubredditSubmission',
            fields=[
                ('id', models.CharField(max_length=128,
                                        primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
