# Generated by Django 2.0.1 on 2018-01-02 19:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit_crawler', '0001_squashed_0003_subredditsubmission_subreddit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=256)),
                ('subreddits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
            ],
        ),
    ]
