# Generated by Django 2.0 on 2018-01-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit_crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('last_crawled', models.DateTimeField(null=True)),
            ],
        ),
    ]
