version: '3'
services:
  web:
    build: .
    entrypoint: gunicorn
    command: ["-b", "0.0.0.0:8000", "-w", "4", "--access-logfile", "-", "reddit_scrapper.wsgi"]
    ports:
      - "8000:8000"
    links:
      - postgres
      - rabbitmq
    env_file: .env.prod
  celery:
    build: .
    entrypoint: celery
    command: ["-A", "reddit_scrapper", "worker", "-B", "-c", "4"]
    links:
      - postgres
      - rabbitmq
    env_file: .env.prod
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "15672:15672"
volumes:
  pgdata:
